// Code generated by pkl-zig. DO NOT EDIT.
pub const ExtendsAbstractClass = @import("ExtendsAbstractClass.pkl.zig").ExtendsAbstractClass;
pub const A = @import("A.pkl.zig").A;
pub const B = @import("B.pkl.zig").B;
pub const C = @import("C.pkl.zig").C;
