// Code generated by pkl-zig. DO NOT EDIT.
pub const ExtendingOpenClass = @import("ExtendingOpenClass.pkl.zig").ExtendingOpenClass;
pub const MyClass = @import("MyClass.pkl.zig").MyClass;
pub const MyOpenClass = @import("MyOpenClass.pkl.zig").MyOpenClass;
pub const MyClass2 = @import("MyClass2.pkl.zig").MyClass2;
