// Code generated by pkl-zig. DO NOT EDIT.
pub const ConfigType = @import("ConfigType.pkl.zig").ConfigType;
pub const ExplicitlyCoolName = @import("ExplicitlyCoolName.pkl.zig").ExplicitlyCoolName;
pub const SomethingVeryFunny = @import("SomethingVeryFunny.pkl.zig").SomethingVeryFunny;
