// Code generated by pkl-zig. DO NOT EDIT.
pub const BugKind = @import("BugKind.pkl.zig").BugKind;
pub const BugKindTwo = @import("BugKindTwo.pkl.zig").BugKindTwo;
pub const BugHolder = @import("BugHolder.pkl.zig").BugHolder;
pub const Bug = @import("Bug.pkl.zig").Bug;
pub const Person = @import("Person.pkl.zig").Person;
pub const Bike = @import("Bike.pkl.zig").Bike;
pub const Wheel = @import("Wheel.pkl.zig").Wheel;
pub const Being = @import("Being.pkl.zig").Being;
pub const ThisPerson = @import("ThisPerson.pkl.zig").ThisPerson;
pub const D = @import("D.pkl.zig").D;
pub const C = @import("C.pkl.zig").C;
pub const B = @import("B.pkl.zig").B;
pub const A = @import("A.pkl.zig").A;
