name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Check formatting
        run: zig fmt --check build.zig src example

  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run unit tests
        run: zig build test

  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install Pkl
        run: |
          curl --fail --location \
            --output pkl \
            https://github.com/apple/pkl/releases/download/0.32.1/pkl-linux-amd64
          chmod +x pkl
          sudo mv pkl /usr/local/bin/pkl
          pkl --version

      - name: Run integration tests
        run: zig build integration-test